### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by antfu** [maru-re/maru#1]
# P0

- [x] 修改資源加載模式，從內嵌改為用戶拖拽上傳，重新定位為“閱讀器”
  - [x] 約定數據格式 (文檔與獨立 npm 包）
  - [x] 集成 valibot 驗證格式
  - [x] 拖拽上傳 UI、數據儲存於 localStorage
  - [x] 支持導入資料夾
  - [x] 歌曲整理 UI (刪除）
    - [x] 基礎歌曲刪除功能
  - [x] 支援導入 zip
  - [x] 支持導出 zip
  - [x] 移除所有內建的歌詞
  - [ ] 更新用戶使用指南
  - [x] Dialog UI 用於展示信息等
- [x] 使用 IndexedDB 
- [x] Discord Server
- [ ] RWD, Mobile layout

# P2

- [x] LRC Parser: https://en.wikipedia.org/wiki/LRC_(file_format)
- [x] i18n
- [x] zh-Hant -> zh-Hans 歌詞翻譯轉換
- [x] Romaji merge `['ha', 'n'] -> ['han']` | `['ka', 'a'] -> ['kaa']`
- [x] Share buttons
- [x] Virtual List for SongsGrid.vue
- [ ] Resizable Player

# P3

- [x] 可视化的歌詞编辑器
